.TH NEWALIASES 1 "June 2010" "The Debian Project" ""
.
.SH NAME
.
newaliases \- pseudo newaliases command for nullmailer
.
.SH SYNOPSIS
.
.B newaliases
.
.SH DESCRIPTION
.
newaliases is a symbolic link to /bin/true and exists for compliance
with the Debian Policy Manual, chapter 11.6, only.
.
.SH SEE ALSO
.
.BR nullmailer (7),
.BR adminaddr (5)
.
.SH AUTHOR
.
Martin A. Godisch <godisch@debian.org>
