.TH nullmailer-qstat 8
.SH NAME
nullmailer-qstat \- summarize status of mail queue
.SH SYNOPSIS
.B nullmailer-qstat
.SH DESCRIPTION
.B nullmailer-qstat
gives a human-readable breakdown
of the number of messages at various spots in the mail queue.

.B nullmailer-qstat
must be run either as
.B root
or as user
.BR mail .
.SH "SEE ALSO"
nullmailer-qread(8)
