.TH nullmailer-qread 8
.SH NAME
nullmailer-qread \- list outgoing messages and recipients
.SH SYNOPSIS
.B nullmailer-qread
.SH DESCRIPTION
.B nullmailer-qread
scans the outgoing queue of messages.
For each message it prints various human-readable information,
including the date the message entered the queue,
the number of bytes in the message,
the message sender,
and all the recipients.

.B nullmailer-qread
must be run either as 
.B root
or with user id
.BR mail .
.SH "SEE ALSO"
nullmailer-qstat(8)
