#!/bin/sh

set -e

. /usr/share/debconf/confmodule
db_version 2.0
db_capb backup

if [ -e /etc/mailname ]; then
	db_set shared/mailname "`cat /etc/mailname`"
else
	db_get shared/mailname
	if [ -z "$RET" ]; then
		db_set shared/mailname "`hostname --fqdn`"
	fi
fi

if [ -e /etc/nullmailer/remotes ]; then
	# Replace newlines with :, then fix any extra : that might turn up.
	db_set nullmailer/relayhost "`cat /etc/nullmailer/remotes | tr '\n' ':' | sed 's/::*/:/g;s/:$//'`"
else
	db_get nullmailer/relayhost
	if [ -z "$RET" ]; then
		db_set nullmailer/relayhost "mail.`hostname --domain`"
	fi
fi

if [ -e /etc/nullmailer/adminaddr ]; then
	db_set nullmailer/adminaddr "`cat /etc/nullmailer/adminaddr`"
else
	db_get nullmailer/adminaddr
fi

state=1
while [ "$state" -ge 1 -a "$state" -le 3 ]; do
	case "$state" in
	1)	db_input high shared/mailname || true
		;;
	2)	db_input high nullmailer/relayhost || true
		;;
	3)	db_input medium nullmailer/adminaddr || true
		;;
	esac
	if db_go; then
		state=$(($state + 1))
	else
		state=$(($state - 1))
	fi
done

db_stop
exit 0
