#! /bin/sh
# postinst script for nullmailer
#
# see: dh_installdeb(1)

set -e

. /usr/share/debconf/confmodule
db_version 2.0

umask 022

case "$1" in
    configure)

		db_get shared/mailname
		echo "$RET" > /etc/mailname

		db_get nullmailer/relayhost
		echo "$RET" | tr ':' '\n' > /etc/nullmailer/remotes

		db_get nullmailer/adminaddr
		if [ "$RET" ]; then
        		echo "$RET" > /etc/nullmailer/adminaddr
		else
		        echo -n > /etc/nullmailer/adminaddr
		fi

		db_stop

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
