#!/bin/sh

set -e

if dpkg --compare-versions "$2" lt-nl 1.00RC7-12; then
	echo "****** NOTE ******"
	echo "The nullmailer init script of $2 is incompatible with the"
	echo "version of nullmailer currently installed. You need to install the new version"
	echo "of /etc/init.d/nullmailer, otherwise the installation process will lock up."
	echo "******************"
fi

exit 0
